<a href="https://colab.research.google.com/github/PRERAN001/Google_collab_files_-project_files-/blob/main/insurance_dector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data=pd.read_csv("/content/insurance.csv")
# data.head()
data.loc[data["sex"]=="female",'sex']=0
data.loc[data["sex"]=="male",'sex']=1
data.loc[data["smoker"]=="yes",'smoker']=0
data.loc[data["smoker"]=="no",'smoker']=1
data.loc[data["region"]=="southwest",'region']=0
data.loc[data["region"]=="southeast",'region']=1
data.loc[data["region"]=="northwest",'region']=2
data.loc[data["region"]=="northeast",'region']=3
# data.replace({"region": {'southeast': 0, 'southwest': 1, 'northeast': 2, 'northwest': 3}})

data

      age sex     bmi  children smoker region      charges
0      19   0  27.900         0      0      0  16884.92400
1      18   1  33.770         1      1      1   1725.55230
2      28   1  33.000         3      1      1   4449.46200
3      33   1  22.705         0      1      2  21984.47061
4      32   1  28.880         0      1      2   3866.85520
...   ...  ..     ...       ...    ...    ...          ...
1333   50   1  30.970         3      1      2  10600.54830
1334   18   0  31.920         0      1      3   2205.98080
1335   18   0  36.850         0      1      1   1629.83350
1336   21   0  25.800         0      1      0   2007.94500
1337   61   0  29.070         0      0      2  29141.36030

[1338 rows x 7 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [ ]:
# fig=plt.figure()
# ax=fig.add_axes([0,0,1,1])
# ax.bar( data["age"].values,data["age"].index)
# plt.show()
# data.shape

In [ ]:
data['sex'].value_counts()

sex
1    676
0    662
Name: count, dtype: int64

In [ ]:
x=data.drop(columns="charges",axis=1)
y=data["charges"]

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [ ]:
x

      age sex     bmi  children smoker region
0      19   0  27.900         0      0      0
1      18   1  33.770         1      1      1
2      28   1  33.000         3      1      1
3      33   1  22.705         0      1      2
4      32   1  28.880         0      1      2
...   ...  ..     ...       ...    ...    ...
1333   50   1  30.970         3      1      2
1334   18   0  31.920         0      1      3
1335   18   0  36.850         0      1      1
1336   21   0  25.800         0      1      0
1337   61   0  29.070         0      0      2

[1338 rows x 6 columns]

In [ ]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,train_size=0.3)

In [ ]:
x_train

      age sex     bmi  children smoker region
352    30   0  27.700         0      1      0
844    53   1  30.495         0      1      3
1234   45   0  27.830         2      1      1
1256   51   0  36.385         3      1      2
698    56   1  33.725         0      1      2
...   ...  ..     ...       ...    ...    ...
715    60   1  28.900         0      1      0
905    26   0  29.355         2      1      3
1096   51   0  34.960         2      0      3
235    40   0  22.220         2      0      1
1061   57   1  27.940         1      1      1

[401 rows x 6 columns]

In [ ]:
model=LinearRegression()
model_=model.fit(x_train,y_train)
predict=model.predict(x_train)
accuracyscore=metrics.r2_score(y_train,predict)
accuracyscore

0.7726724331160439

In [ ]:
predict=model.predict(x_test)
accuracyscore=metrics.r2_score(y_test,predict)
accuracyscore

0.7366306455978993

In [ ]:
import pandas as pd
import numpy as np
input_data = pd.DataFrame([{
    'age': 51,
    'sex': 1,
    'bmi': 22.3,
    'children': 1,
    'smoker': 1,
    'region': 0
}])

# 46,female,33.44,1,no,southeast,
predict = model.predict(input_data)
print(predict)

[7939.65834762]